@extends('internal.layout')

@section('title', 'Gán nhãn ngày')

@section('head')
<link rel="stylesheet" href="{{$_ENV['URL_INTERNAL_BASE']}}/css/calendar.css">
<script type="module" src="{{$_ENV['URL_INTERNAL_BASE']}}/js/gan-ngay.js" defer></script>
@endsection

@section('breadcrumbs')
<li>
    <div class="flex items-center">
        <svg class="flex-shrink-0 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
        </svg>
        <span class="ml-4 text-sm font-medium text-gray-500">Gán nhãn ngày</span>
    </div>
</li>
@endsection

@section('content')
<div class="bg-white shadow rounded-lg p-6">
    <h1 class="text-2xl font-semibold text-gray-900 mb-6">Gán nhãn ngày</h1>
    
    <div class="mb-6">
        <p class="text-gray-600">
            Chọn và gán nhãn cho các ngày đặc biệt (ngày lễ, ngày tết) để áp dụng các chính sách phụ thu giá vé và tính toán lương nhân viên.
        </p>
    </div>
    
    <!-- Calendar Controls -->
    <div class="flex justify-between items-center mb-4">
        <div class="flex items-center space-x-4">
            <button id="prev-month" class="bg-gray-200 hover:bg-gray-300 text-gray-700 font-bold py-2 px-4 rounded inline-flex items-center">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
                </svg>
                Tháng trước
            </button>
            <button id="next-month" class="bg-gray-200 hover:bg-gray-300 text-gray-700 font-bold py-2 px-4 rounded inline-flex items-center">
                Tháng sau
                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 ml-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                </svg>
            </button>
        </div>
        <h2 id="current-month-year" class="text-xl font-semibold text-gray-800">Tháng 9, 2025</h2>
    </div>
    
    <!-- Calendar -->
    <div class="overflow-x-auto">
        <table class="w-full border-collapse">
            <thead>
                <tr>
                    <th class="border p-2 bg-gray-100 text-gray-600">CN</th>
                    <th class="border p-2 bg-gray-100 text-gray-600">T2</th>
                    <th class="border p-2 bg-gray-100 text-gray-600">T3</th>
                    <th class="border p-2 bg-gray-100 text-gray-600">T4</th>
                    <th class="border p-2 bg-gray-100 text-gray-600">T5</th>
                    <th class="border p-2 bg-gray-100 text-gray-600">T6</th>
                    <th class="border p-2 bg-gray-100 text-gray-600">T7</th>
                </tr>
            </thead>
            <tbody id="calendar-body" data-url="{{$_ENV['URL_WEB_BASE']}}">
                <!-- Calendar days will be generated by JavaScript -->
            </tbody>
        </table>
    </div>
    
    <!-- Legend -->
    <div class="mt-4 flex space-x-6">
        <div class="flex items-center">
            <div class="w-4 h-4 bg-gray-200 rounded mr-2"></div>
            <span class="text-sm text-gray-600">Ngày thường</span>
        </div>
        <div class="flex items-center">
            <div class="w-4 h-4 bg-blue-200 rounded mr-2"></div>
            <span class="text-sm text-gray-600">Ngày lễ</span>
        </div>
        <div class="flex items-center">
            <div class="w-4 h-4 bg-red-200 rounded mr-2"></div>
            <span class="text-sm text-gray-600">Ngày Tết</span>
        </div>
        <div class="flex items-center">
            <div class="w-4 h-4 bg-gray-300 rounded mr-2"></div>
            <span class="text-sm text-gray-600">Ngày không thể gán (quá khứ)</span>
        </div>
    </div>
</div>

<!-- Modal Dialog for Date Information -->
<div id="date-modal" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center hidden z-50">
    <div class="bg-white rounded-lg shadow-lg w-full max-w-md p-6">
        <div class="flex justify-between items-center mb-4">
            <h3 class="text-xl font-semibold text-gray-900">Thông tin Ngày</h3>
            <button id="close-modal" class="text-gray-400 hover:text-gray-500">
                <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                </svg>
            </button>
        </div>
        
        <form id="date-form">
            <input type="hidden" id="selected-date" name="selected-date">
            
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="display-date">
                    Ngày
                </label>
                <div id="display-date" class="py-2 px-3 bg-gray-100 rounded text-gray-800"></div>
            </div>
            
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="date-type">
                    Loại ngày
                </label>
                <select id="date-type" name="date-type" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
                    <option value="Ngày thường">Ngày thường</option>
                    <option value="Ngày lễ">Ngày lễ</option>
                    <option value="Ngày tết">Ngày Tết</option>
                </select>
            </div>
            
            <div id="special-day-name-container" class="mb-4 hidden">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="special-day-name">
                    Tên ngày đặc biệt
                </label>
                <input type="text" id="special-day-name" name="special-day-name" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" placeholder="Ví dụ: Giỗ Tổ Hùng Vương, Tết Nguyên Đán">
                <p id="special-day-error" class="text-red-500 text-xs italic mt-1 hidden">Vui lòng nhập tên ngày đặc biệt</p>
            </div>
            
            <div class="flex justify-end mt-6">
                <button type="button" id="save-date" class="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                    Lưu
                </button>
            </div>
        </form>
    </div>
</div>

<!-- Toast Notification -->
<div id="toast-notification" class="fixed bottom-4 right-4 bg-green-500 text-white px-4 py-2 rounded shadow-lg transform transition-transform duration-300 translate-y-20 opacity-0">
    Cập nhật gán nhãn ngày thành công
</div>
@endsection